export const Paths = {
	login: "/login",
	mypage: "/mypage",
	editProfile: "/profile/edit",
	reservation: "/reservation",
	dashboard: "/dashboard",
	selectionInfo: "/selection/information",
	selectionSolution: "/selection/solution",
	showEvent: "/events/:id",
	showCaseStudy: "/case/studies/:id",
	caseStudyHistory: "/case/studies/history",
	caseStudyCorrection: "/case/studies/correction",
	showCompany: "/companies/:id",
	showMenter: "/menters/:id",
	entrySheetCorrection: "/entry/sheets/correction",
	ticketPurchase: "/tickets/purchase",

	// admin path
	adminLogin: "/admin/login",
	adminDashboard: "/admin/dashboard",
	adminMentees: "/admin/mentee/list",
	adminEditMentee: "/admin/mentee/edit/:id",
	adminRegisterMentee: "/admin/mentee/register",
	adminMenters: "/admin/menter/list",
	adminEditMenter: "/admin/menter/edit/:id",
	adminRegisterMenter: "/admin/menter/register",
	adminEvents: "/admin/event/list",
	adminEditEvent: "/admin/event/edit/:id",
	adminCreateEvent: "/admin/event/create",
	adminCaseStudies: "/admin/case/study/list",
	adminEditCaseStudy: "/admin/case/study/edit/:id",
	adminCreateCaseStudy: "/admin/case/study/create",
	adminEntrySheets: "/admin/entry/sheet/list",
	adminEditEntrySheet: "/admin/entry/sheet/edit/:id",
	adminCreateEntrySheet: "/admin/entry/sheet/create",
}